### ISSUE TITLE
User avatar is not an absolute URI reference

### ISSUE THREAD

**Issue by tbroyer** [ozwillo/ozwillo-portal#184]
The profile avatar is stored only as a path (e.g. `/img/my/avatar/img-20.png`). Not only this is wrong, but it also makes it impossible for applications to retrieve/display the image without knowledge of the base URI against which to resolve the relative URI reference.

As soon as this issue is fixed in the Portal, I'll add checks in the Kernel to require an absolute URI reference.

**Comment by bobeal** [comment]
Removed avatar feature in the rewritten profile page
