### ISSUE TITLE
Possibility to invite an app_user outside the admin organization

### ISSUE THREAD

**Issue by silently** [ozwillo/ozwillo-portal#207]
This scenario is needed for agrilocal: the possibility, for a given app instance purchased by an org/or personal use, to add an app_user who's not part of the buying entity.

See the current behavior client-side https://github.com/pole-numerique/oasis-portal/blob/master/portal-parent/oasis-portal-front/src/main/resources/public/js/appmanagement/myapps.jsx.js#L186

@tbroyer: do you confirm the portal can call the kernel with just an email?

**Comment by mdutoo** [comment]
Done on Kernel side.

Portal UI specs:
in the app users modal, add below the list of app users (which now includes users outside the app's own org), just as in the Network page:
- a button "Invite" which displays the same modal as on the Network page, but calls (the Portal and then the) new Kernel API
- the list of current (not yet  approved) invitations, just as on the Network page
