### ISSUE TITLE
Adding new Dashboard with no name & overflown edition buttons

### ISSUE THREAD

**Issue by ilucatero** [ozwillo/ozwillo-portal#224]
It is possible to add new Dashboards without a name, which in UX viewpoint is not right since it seems to be an empty space between buttons.

Other bug is when the screen is resized smaller, there the edition buttons overflown the desktop name area.

See the below image:

![capture du 2015-06-18 13 44 10](https://cloud.githubusercontent.com/assets/12236126/8230535/713970d6-15c1-11e5-8252-a59e61100931.png)

**Comment by bobeal** [comment]
Fixed with the new design
