### ISSUE TITLE
Auto-load ZIP code while selecting a city

### ISSUE THREAD

**Issue by ilucatero** [ozwillo/ozwillo-portal#228]
During the organization creation/modification in MyNetwork, on tab "Address and Géoloc" : 

Today, when a city is selected the "zip/postal code" field is set with 0000 and the users can change it.

What now is required on this field to be auto-loaded with the selected city's zip code (it should remain modifiable so the uses can change it in case is doesn't correspond to its real one).

**Comment by bobeal** [comment]
Done in Profile page. There is another ticket for the Network side of this feature (#331). So I'm closing this ticket.
