### ISSUE TITLE
Profile country can be filled with anything, requires redoing as jsx

### ISSUE THREAD

**Issue by ilucatero** [ozwillo/ozwillo-portal#229]
Currently the inputbox Address->Country in the profile page can be set with any input. This is not good since the user can insert non existing countries or even a country name with a labelled wrongly (e.g. ïtaly, Frantzia, or Spania).

These labels should be selected over options loaded from any standard source like datacore, and should also be inserted with the original country label (France, España, Türkiye, etc.).

The correct user's profile data is important for the good site performance because it is used on other processes like searching organization or buying apps.

**Comment by bobeal** [comment]
Country selection from DC data has been implemented.
