### ISSUE TITLE
Redo Profile in react (jsx)

### ISSUE THREAD

**Issue by mdutoo** [ozwillo/ozwillo-portal#241]
To unify UI underlaying tech, and allow reusing existing jsx components to link to geo data #229 #230 .

**Comment by bobeal** [comment]
And do not forget to remove dead code used to manage the profile view

**Comment by bobeal** [comment]
* It is possible to set an empty value for the locale ... but it breaks the whole app
* There are React warnings in the logs
* Nickname is mandatory but can be set to empty without an error validation when submitting
