### ISSUE TITLE
i18n untranslated English messages

### ISSUE THREAD

**Issue by ilucatero** [ozwillo/ozwillo-portal#265]
It will be required to translate all added or modified message for the v1.1

**Comment by OzBruno** [comment]
Some translation are missing on the Bulgarian interfaces : "Catalog" and "Discover"
![capture](https://cloud.githubusercontent.com/assets/11058387/11472710/c012f0f4-976e-11e5-9666-c5c621bf4ee6.PNG)

**Comment by MLE-Astek** [comment]
Some relation with [this](https://github.com/ozwillo/ozwillo-portal/issues/269) ?
