### ISSUE TITLE
Bulgarian Store Link text overlaps the data link

### ISSUE THREAD

**Issue by ilucatero** [ozwillo/ozwillo-portal#269]
See below image

![issue-new16092015](https://cloud.githubusercontent.com/assets/12236126/9932177/1c222ad4-5d42-11e5-9700-6805586465f2.png)

Also, the "Discover" dropdown menu is not translated...

**Comment by bobeal** [comment]
Should be resolved with the new design. To re-open if it's not the case.

**Comment by divanski** [comment]
Yes, I see.
