### ISSUE TITLE
Can't modify the name of an existing organisation

### ISSUE THREAD

**Issue by OzBruno** [ozwillo/ozwillo-portal#274]
On the network tab, when clicking on the "information" button of an organisation, the name of this organisation should be editable by an org_admin
![capture](https://cloud.githubusercontent.com/assets/11058387/10285474/4f4a2c04-6b89-11e5-985e-f97113f23d0b.PNG)

**Comment by MLE-Astek** [comment]
Fixed [commit](https://github.com/ozwillo/ozwillo-portal/commit/9f25cf25d374f4dc9740ec2e2a394a0f342f02ad) & [PR](https://github.com/ozwillo/ozwillo-portal/pull/332)
