### ISSUE TITLE
Impact on new visibility and access_control properties come from Kernel

### ISSUE THREAD

**Issue by MLE-Astek** [ozwillo/ozwillo-portal#298]
A new kind of visibility (NEVER_VISIBLE) is now present on some data from Kernel. We have to evaluate all impacts of this modification.

https://github.com/ozwillo/ozwillo-kernel/commit/5f1beee5623517a2fdf0326d7bb87845beb0564b

**Comment by bobeal** [comment]
* Currently not handled at all in My Apps

**Comment by bobeal** [comment]
* In the store, an application that does not have the "visible" property set to true does not show up (even if it has the correct "visibility" and "access_control" properties)

**Comment by flaussinot** [comment]
Visibility and AccessControl are always overwrite by visible and restricted properties.
We can't manage them directly.

https://github.com/ozwillo/ozwillo-kernel/commit/5f1beee5623517a2fdf0326d7bb87845beb0564b
@tbroyer

**Comment by tbroyer** [comment]
Not sure I understand your comment here, but it looks like you missed this commit in the Kernel https://github.com/ozwillo/ozwillo-kernel/commit/7a03fc0f45d062f8708ff190bf14b6edd65e284b (have a look at the table-driven test in there for the details/contract).

What clients of the API (including the portal) need to do, is to work with those 4 fields, and, to simplify things, it means:

- only ever look at and modify `visibility` and `access_control`
- always unset `visible` and `restricted` (or set them to `null`) to make sure they won't overwrite the `visibility` and `access_control` fields.

`visible` and `restricted` are there for backwards compatibility only, for those clients that haven't been updated to `visibility` and `access_control` (and those properties haven't been documented yet, pending for the Portal update to make sure it won't mess with providers' efforts to update; which means that nobody has updated yet to use those new properties and capabilities)
