### ISSUE TITLE
Cataloge doesn't work when not connected

### ISSUE THREAD

**Issue by MLE-Astek** [ozwillo/ozwillo-portal#312]
In preproduction there the loading animation indefinitely …

**Comment by tbroyer** [comment]
Browser console shows error `Uncaught ReferenceError: default_org_data is not defined`, and indeed that was removed in c3ab7f9a666df68152eadd1f40e40b1602b36a34

**Comment by bobeal** [comment]
Ouch, clearly did not spotted this hidden dependency from store component. I'm working on it.
