### ISSUE TITLE
Unable to logout from production

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#313]
When I logout from production :
- A brief red box appears just below the logout button
- Then I'm redirect to either :
  - a blank page (like https://portal.ozwillo.com/callback?state=...)
  - the catalog like if I was logged out but when I click on the Login button, I'm redirected to the portal  without re-authenticating
  - the page I was in before trying to log out

This happens at least 4 out of 5 times.

**Comment by bobeal** [comment]
Check that it has no impact on other AJAX requests issued by the portal.

**Comment by MLE-Astek** [comment]
The fix no covert all use case, some times we reproduce the problem but is much less than before

**Comment by bobeal** [comment]
Not encountered for a while.
