### ISSUE TITLE
Incorrect form validation prevents installing applications

### ISSUE THREAD

**Issue by schambon** [ozwillo/ozwillo-portal#317]
Scenario: try to install a free app for citizens from the app store (I'm testing with a Citizen Kin procedure but it could be anything)

The store shows a dialogue inviting the user to enter her name and address (pulled from the profile initially):

![screenshot from 2015-11-13 15 37 28](https://cloud.githubusercontent.com/assets/2110554/11148377/b858c618-8a1c-11e5-84d6-331616849769.png)

Expected: clicking "Next" takes the user to the next page of the dialogue.
Actual: the "City" and "Country" fields are highlighted in red as if they weren't filled in and the dialogue remains at the same page.

Consequence: it is impossible to buy an app.

**Comment by bobeal** [comment]
Workaround until I fix it : if you re-set country then city, you can go to next step.

**Comment by bobeal** [comment]
I thought it was a bug introduced by the refactoring made for the issue #303 but this bug already exists in production.

**Comment by MLE-Astek** [comment]
Tested
