### ISSUE TITLE
Cannot delete an application

### ISSUE THREAD

**Issue by schambon** [ozwillo/ozwillo-portal#326]
**In dev environment**

Scenario: go to My Apps. Pick an application for one of the organizations you're admin of. Click Delete.

Expected: either a confirmation dialog or the application being deleted.

Actual: 400 Bad Request.

Coupled with #324  and #317  it makes it pretty complicated to test application provisioning.

**Comment by mdutoo** [comment]
The Kernel patch has been deployed in dev, so @schambon could you check it works ? (I'm afraid to delete an app that you're actually being working on right now)

**Comment by schambon** [comment]
Thanks, it appears to be working.

**Comment by mdutoo** [comment]
Great, closing.
