### ISSUE TITLE
Cannot install an application for professional use for a new organization

### ISSUE THREAD

**Issue by schambon** [ozwillo/ozwillo-portal#327]
**in development environment**

Scenario: navigate to App Store. Select an app that's targeted at Public Bodies only (e.g. Citizen Kin, which is what I'm trying to test). Click Install. "For professional use" is the only choice in the first selection and the Contact section is filled with your profile information.

In the Organization section, select "New organization", "Public body" then enter a name and SIRET. Follow the wizard through.

Expected: the application is installed (or at least, the application's provisioning endpoint receives a provisioning request)

Actual: an error saying the application can't be installed. Looking at the portal's logs it looks like it has issued the kernel with a request to provision the app for the citizen instead of the newly-created organization.

**Comment by bobeal** [comment]
Also fixed by fe488af8ad53627a218bc0eee47188e3dce45756 (ticket #324). 

Fix available on master and on dev & pre-prod platforms tomorrow morning.

**Comment by MLE-Astek** [comment]
Tested OK, be aware of what application will be installed, with some (old, deprecated, …) it's say «installation success» but it doesn't appear on dashboard.
