### ISSUE TITLE
Cataloge page field layout

### ISSUE THREAD

**Issue by MLE-Astek** [ozwillo/ozwillo-portal#333]
On the left of the catalogue page there 2 search bar stack. On top is the geographical filter but there nothing to indicate this, the second filter on the name of the application.
It will be more logical to reverse and add a indication for the geo filter.

**Comment by bobeal** [comment]
Redesigned with new design (so to speak).

**Comment by mdutoo** [comment]
For the record, the original idea was that all searches had to be geolocalized, such as it would happen transparently on a smartphone, so that local services such as provided by the current city always come out / on top.
