### ISSUE TITLE
Handle translation of notifications

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#336]
Currently, notifications are only displayed in english.

In the JSON data received from the kernel, messages and actions labels are provided in the different supported languages but those are not handled by the portal.

For instance, here is a sample notification : 

```
{
"id":"XXX",
"user_id":"YYY",
"instance_id":"ZZZ",
"message":"This application is now available and ready to use.",
"message#es-ES":"Esta aplicación esta ahora disponible y lista para ser utilizada.",
"message#it-IT":"Questa applicazione è adesso disponibile e pronta all'uso.",
"message#ca-ES":"Aquesta aplicació està disponible i preparada per a ser utilitzada.",
"message#tr-TR":"Bu uygulama artık kullanıma hazırdır.",
"message#fr-FR":"Cette application est disponible et prête à l'emploi.",
"message#bg-BG":"Приложението вече е достъпно и готово за ползване.",
"action_uri":"https://portal.ozwillo-dev.eu/my/appsmanagement",
"action_label":"Settings",
"action_label#es-ES":"Configuración",
"action_label#it-IT":"Impostazioni",
"action_label#ca-ES":"Configuració",
"action_label#tr-TR":"Ayarlar",
"action_label#fr-FR":"Settings",
"action_label#bg-BG":"Настройки",
"time":1448292658571,
"status":"UNREAD",
"modified":1448292658571
}
```

**Comment by mdutoo** [comment]
FYI:
the portal computes the best locale for a user among supported ones (OasisLocales.values() = fr, es, ca, it, bg, tr, en), using java.ui.Locale.lookup(userLocalePriorityList, availableLocales) :
https://github.com/ozwillo/ozwillo-portal/blob/master/portal-parent/ozwillo-portal-front/src/main/java/org/oasis_eu/portal/services/NameDefaults.java#L32

**Comment by MLE-Astek** [comment]
The 3 concerned commits in the java-spring-integration project [1](https://github.com/ozwillo/ozwillo-java-spring-integration/commit/776008687402151500d77f47a6739c513bd22aa9), [2] (https://github.com/ozwillo/ozwillo-java-spring-integration/commit/9bc6272eb3e11039f788389a63835e2e9e942c61) & [3](https://github.com/ozwillo/ozwillo-java-spring-integration/commit/b675074b62a849992583b8508604f762bdf8bebc)
