### ISSUE TITLE
Sorting on apps in Notifications screen does not work

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#343]
Fails with a JS error : 

```
Uncaught TypeError: Cannot read property 'localeCompare' of null
```

Error happens in https://github.com/ozwillo/ozwillo-portal/blob/master/portal-parent/ozwillo-portal-front/src/main/resources/public/js/notifications.jsx.js#L54.

**Comment by tbroyer** [comment]
Safari user ? (or IE<11)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Browser_compatibility

**Comment by bobeal** [comment]
Nope, I'm on Chrome and FF.

I think the problem is that it calls localeCompare on a null object (a notification message is not necessarily associated to an application).

**Comment by tbroyer** [comment]
Hah, read the error message too fast and jumped clicked on the link ;-)

**Comment by bobeal** [comment]
Yes, you're right, we have to replace this use of localeCompare.

**Comment by MLE-Astek** [comment]
Witch replacement ?
* [Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator#Browser_compatibility) is worst for browser support
* [s1 < s2 ? -1 : s1 > s2 ? 1 : 0;](https://jsperf.com/localecompare/32), will be hazardous for non English language

For [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Browser_compatibility) the basic support doesn't specify the version of IE, is for locale parameter support. If I see on Microsoft site i found [this](https://msdn.microsoft.com/en-us/library/casyzyb5%28v=vs.90%29.aspx) who said is compatible with IE 5.5 version. So without language parameter i think it's OK. Right ?

**Comment by tbroyer** [comment]
I think I misread the compatibility table in MDN (read it too fast, missing the first line). Yes `localeCompare` is OK as used here. Sorry for the noise.

**Comment by bobeal** [comment]
Hmm, I'm not completely convinced ...

![screen shot 2015-12-07 at 15 25 13](https://cloud.githubusercontent.com/assets/175382/11629252/570732e4-9cf7-11e5-80dd-d9f83c952fe9.png)

**Comment by MLE-Astek** [comment]
Sure, there something wrong …
