### ISSUE TITLE
Disallow the edition of email field

### ISSUE THREAD

**Issue by MLE-Astek** [ozwillo/ozwillo-portal#345]
In the profile page you can modify your email but it's not saved when you clic on «save change». There no error message and the email is not updated.

**Comment by tbroyer** [comment]
Updating the email address is a sensitive operation (as sensitive as changing your password), and is not currently handled on the Kernel (there'd need to be mails sent to both addresses with a validation link –like we do on sign up–, and a way to reach Ozwillo to tell e.g. your account has been hacked and the hacker changed the password and email address and you'd like a manual intervention at Ozwillo to recover your account).

So the email field should not be editable like any other "simple data" field.

**Comment by bobeal** [comment]
It should also be removed from app install form (see screenshot).

![screen shot 2015-12-07 at 10 12 23](https://cloud.githubusercontent.com/assets/175382/11623156/325b128e-9ccb-11e5-83b2-5b47859589ed.png)

**Comment by MLE-Astek** [comment]
Fix https://github.com/ozwillo/ozwillo-portal/pull/350
