### ISSUE TITLE
Possibility to have just a space for Nickname

### ISSUE THREAD

**Issue by MLE-Astek** [ozwillo/ozwillo-portal#346]
There possibility to have just a space for nickname, also we can copy another nickname and add a space for user usurpation.

**Comment by tbroyer** [comment]
Is that really impersonation? There's no unicity on nicknames so you can also just copy someone else's nickname, no need to add a space. Homonyms are a reality that we (people) have to deal with, and nicknames are not "usernames" in Ozwillo..
