### ISSUE TITLE
HTML tags in kernel timeout error

### ISSUE THREAD

**Issue by vdachev** [ozwillo/ozwillo-portal#356]
You can see HTML in a timeout error reported by the portal when trying to do something with the kernel (not quite sure what exactly).

BTW, timeout issues come out often and something should be done about them as well.

![capture](https://cloud.githubusercontent.com/assets/6223745/11893096/0e174b30-a56e-11e5-83a4-0b22ecbd9598.PNG)

**Comment by bobeal** [comment]
Not seen for a long time.
