### ISSUE TITLE
Prod/modal orga: autocompletion of activity code (NAF) failed after the 3rd character

### ISSUE THREAD

**Issue by OzBruno** [ozwillo/ozwillo-portal#357]
Searching for 01.11Z code, entering "01." displays right results
![image3](https://cloud.githubusercontent.com/assets/11058387/11995570/5b617ae8-aa53-11e5-9737-d4351b481a5e.png)
but entering one more digit causes a failure
![image4](https://cloud.githubusercontent.com/assets/11058387/11995582/73cca698-aa53-11e5-9a0a-da2a22d22388.png)

**Comment by bobeal** [comment]
The query fails with the following error : 

```
| DEBUG| 2015-12-29 08:39:57.438 | org.oasis_eu.spring.datacore.impl.DatacoreClientImpl - Fetching limited Resources: URI String is https://data.ozwillo.com/dc/type/orgact:Activity_0?start=0&limit=10&orgact:code=$regex%5E01.4&orgact:country=http://data.ozwillo.com/dc/type/geocofr:Pays_0/FR
| INFO | 2015-12-29 08:39:58.654 | kernelLogging.logFullErrorResponses - Full response body: {"code":"org.oasis.datacore.core.entity.query.QueryException","causes":[],"location":"org.oasis.datacore.core.entity.query.ldp.LdpEntityQueryServiceImpl.executeMongoDbQuery(LdpEntityQueryServiceImpl.java:786)","message":"Query or sort with non indexed fields has reached maxScan (300) before document limit (found 8<10) , meaning some documents can't be found without prohibitive cost. Use only indexed fields, or if you really want the few documents already found lower limit, or if in Model design mode add indexes. Retry in debug mode to get more information."}
| WARN | 2015-12-29 08:39:58.654 | org.oasis_eu.spring.util.KernelLoggingInterceptor - GET request to https://data.ozwillo.com/dc/type/orgact:Activity_0?start=0&limit=10&orgact:code=$regex%5E01.4&orgact:country=http://data.ozwillo.com/dc/type/geocofr:Pays_0/FR resulted in 400 Bad Request
```

When I launch this query directly in the DC playground, I get the same error whatever the orgact:code regex is (tried with %5E01, %5E01., ...)

@mdutoo what's the best way to deal with this ?

**Comment by mdutoo** [comment]
Well, this is the first item in the Playground FAQ.

As the error says, the query uses non indexed fields and is therefore inefficient and has been aborted to avoid hampering performances. So these fields should be indexed (queryLimit > 0 ex. 100) in the master model. Once the master model has been updated, the query can be checked again in the Playground.

**Comment by OzBruno** [comment]
The master model has been updated with positive query limit on activity code of each country, and it works
