### ISSUE TITLE
In prod mongo, big latency and BV out of sync, because of BV geo replication every 30s

### ISSUE THREAD

**Issue by mdutoo** [ozwillo/ozwillo-portal#361]
because Prod BV geo replication conf was:

    #replication: 0 0 1 * * 3   # Once a week on Tuesday at 1am
    replication: 0 0/5 * * * ?   #Runs every 30 sec / should be run only in BV for DB cache update

Needless to say, I commented out the second, which is quite mindless, and uncommented the first.

Details about finding it out and putting the cluster back up are at pole-numerique/oasis-datacore-puppet#5. So this issue is only a shortcut to it, so that it can be sorted out at portal level:
- I don't know who did it, but was it only for a one time operation, though the comment would say otherwise ?
- or is there any reason behind it, though nobody should create geo areas ?
- maybe some dc geo areas have to be patched manually to allow end users go on creating ex. their orgs, and therefore replication should be done as soon as possible ??).

**Comment by bobeal** [comment]
I don't know who did that, nor what was the reason.

It's probably here for months ...
