### ISSUE TITLE
Portal doesn't set org:country field

### ISSUE THREAD

**Issue by mdutoo** [ozwillo/ozwillo-portal#363]
(from ozwillo/ozwillo-datacore#150)

Indeed, the portal's Network page sets the adrpost:country field:
https://github.com/ozwillo/ozwillo-portal/blob/master/portal-parent/ozwillo-portal-front/src/main/java/org/oasis_eu/portal/services/dc/organization/DCOrganizationService.java#L337

but it does not set the org:country field, as it is visible in this code.

(and re-check every other org field as well, by the way)

**Comment by bobeal** [comment]
You are pointing to the method used to generate the DC id which, afaik, is correct.

The org:country field should be set in the [mergeDCOrgToDCResources method](https://github.com/ozwillo/ozwillo-portal/blob/master/portal-parent/ozwillo-portal-front/src/main/java/org/oasis_eu/portal/services/dc/organization/DCOrganizationService.java#L278). 

And the org:country field seems to be a collateral damage of this July 2015 commit : https://github.com/ozwillo/ozwillo-portal/commit/878fe7d8c5fcc1c16c3ca81bd401e7d07e43ada2#diff-5cc277725c3328017e34729e6cbced73R169.

While I'm on it, is org:country the only missing field, wrt to the organizations' DC model ?

**Comment by mdutoo** [comment]
That's exactly what my last line of comment was about.

**Comment by tbroyer** [comment]
AIUI, `org:country` is intimately linked to the resource type, so it should be set once at creation time and never changed afterwards. Marc pointed to the code that populates those things, QED.

**Comment by mdutoo** [comment]
An alternative is to set, in the org model, adrpost:country's aliasedStorageNames to adrpost:country so that the first one is stored in the second one (though the opposite would be conceptually better). This requires to re-import the metamodel, and re-save all existing orgs (MLE's script could be reused).
