### ISSUE TITLE
Limited number of instance allowed for one organisation 

### ISSUE THREAD

**Issue by huseyinunsal78** [ozwillo/ozwillo-portal#364]
After the latest changes in the Portal, it is not possible to deploy only one instance on behalf of the same organisation. I tried associating different users with the same organisation using the social network feature; however I still receive an error message. We wish to be able to buy more than one instance per one organisation. 
 
e.g. We are using two instances of INVPROM that has already been deployed before the change. We need to be able to buy more instances of INVPROM on behalf of EMDA (with the registered Tax ID), without needing to create fake users with fake Tax IDs.

One instance for Turkish speaking end-users at Regional scale
One instance for English speaking end-users at Regional scale
5 instance for Turkish speaking end-users at provincial scale (each province of East Marmara)

**Comment by bobeal** [comment]
Hi Huseyin,

There is nothing in the portal preventing an organization to deploy more than one instance of an application (but apps can prevent it).

What error message are you receiving ?

**Comment by bobeal** [comment]
Btw, I've just instanciated two Invprom on the same organization and it worked (see attached screenshot).

![screen shot 2016-01-25 at 15 41 51](https://cloud.githubusercontent.com/assets/175382/12553935/55e7c0aa-c37a-11e5-81eb-4a33e097b292.png)

**Comment by huseyinunsal78** [comment]
Hi Benoit,

Ok, thank you, it was while ago when I tried and failed to do so. I'll try
again these days.

Best regards,

Hüseyin

25 Ocak 2016 Pazartesi tarihinde, Benoit Orihuela <notifications@github.com>
yazdı:

> Btw, I've just instanciated two Invprom on the same organization and it
> worked (see attached screenshot).
>
> [image: screen shot 2016-01-25 at 15 41 51]
> <https://cloud.githubusercontent.com/assets/175382/12553935/55e7c0aa-c37a-11e5-81eb-4a33e097b292.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozwillo/ozwillo-portal/issues/364#issuecomment-174526975>
> .
>


-- 
Hüseyin Özgür Ünsal
