### ISSUE TITLE
Allow an organization to change its registration number

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#370]
* With handling of unauthorised use cases (eg the resource already exists in the datacore)
* With handling of aliases
 * Display them ?
 * @tbroyer do we have to tell the kernel about the new URI or can he live with the old one ?
* And probably more functional details to be added ...

**Comment by tbroyer** [comment]
We **will** have to live with the old one anyway when the change is driven by an application, but better update the value to the "canonical" ID when it's done by the portal.

BTW, when calling `/d/org?dc_id=…` to check whether an organization is "owned" in the Kernel, the Portal would have to check **all** IDs, not just the canonical one.  
We should probably allow multiple `dc_id` values to be passed at that endpoint on the Kernel and do an optimized search (1 vs. N requests, at each level: HTTP + MongoDB)
