### ISSUE TITLE
Handling of apps instances in My Apps page

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#375]
For instance, applications instances are ignored if the application is not visible for the user (see 
https://github.com/ozwillo/ozwillo-portal/blob/3459a64a7eed52b510bdb060487436e4c8bee25b/src/main/java/org/oasis_eu/portal/services/PortalAppManagementService.java#L111-L114), which is not a correct way to handle them.

What's more, there are caching issues that can still make it visible (sometimes) to the user ...

**Comment by tbroyer** [comment]
Can we bump the priority even higher? Customer now (rightfully) complains about the workaround (which was to set the application as visible in the store)

**Comment by bobeal** [comment]
No pb. I added it in the 1.45.0 milestone.
