### ISSUE TITLE
Impossible to delete an Organization

### ISSUE THREAD

**Issue by Julien-Hautemaniere** [ozwillo/ozwillo-portal#399]
When you want to delete an organization, you have the error message "Organization has running (or pending) application instances", even if you have no application installed with this organization.

Tested with the organizations : "Test de julien", Test 2 de Julien".

![pb ozwillo](https://user-images.githubusercontent.com/25898468/27219218-37dc831a-5281-11e7-8ab6-6240121c5956.png)

**Comment by tbroyer** [comment]
There are four pending instances of “Hotspots Wifi Cigale” for organization “Test de Julien”, and one for organization “Test 2 de Julien”; so the error is expected.

I don't think the Ozwillo Portal has any way of deleting pending instances though.

**Comment by Julien-Hautemaniere** [comment]
There are no apps visible in my Dashboard.

![pb_ozwilloo](https://user-images.githubusercontent.com/25898468/27222257-de458328-528b-11e7-8a47-10bab8109d02.png)

**Comment by bobeal** [comment]
@Julien-Hautemaniere you have probably removed pending instances from your dashboard
@tbroyer anything against displaying pending instances for an organization and allowing an org admin to delete one ?

**Comment by tbroyer** [comment]
> anything against displaying pending instances for an organization

On the contrary!

> and allowing an org admin to delete one ?

We need to carefully think about the implications for the providers: how/when they'll detect it, etc.

But displaying the pending instances would be a first step. At least the error message reported here would start to make sense. And if the pending instances are actually "in error" on the provider side (for whichever reason), users could contact the provider (first), then possibly contact us for support (and then we could delete them cleanly; we have a command-line tool for that)

**Comment by bobeal** [comment]
For the first part : displaying the pending instances.
