### ISSUE TITLE
Error message after a successful invitation to join an organization

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#400]
Whereas the invitation email has been successfully sent (and received).

**Comment by OtakuDigitChoc** [comment]
I can't reproduce the error, I tried several times the invitation and I did not have any error ..

**Comment by bobeal** [comment]
Even when tried on the preprod platform ?

**Comment by OtakuDigitChoc** [comment]
Even

**Comment by bobeal** [comment]
Ok, we'll have a look at it together next week.

**Comment by bobeal** [comment]
Sometimes, the portal issues two invitations requests to the kernel and, of course, the second one fails with a 409, thus the error message.

To be looked at after but not a regression of the 1.48.
