### ISSUE TITLE
Wrong invitation date displayed in "manage users" window

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#406]
All dates are set to current date :

![screenshot from 2017-11-09 11-05-36](https://user-images.githubusercontent.com/175382/32599877-209be774-c53e-11e7-971d-39efb0ce3862.png)

**Comment by bobeal** [comment]
Same problem for the "push to dashboard" window

**Comment by Nicoletti-Seb** [comment]
Issue was already fix in developer branch
