### ISSUE TITLE
Search organizations: data are incompletes 

### ISSUE THREAD

**Issue by Nicoletti-Seb** [ozwillo/ozwillo-portal#415]
Test (on localhost to prepod server):
In form to create an organization: 
- API: /my/api/network/search-organizations (spring side)
- Fields "legal_name" and "city" are nulls
![capture d ecran 2018-01-10 a 10 21 13](https://user-images.githubusercontent.com/9880577/34764912-34a09660-f5f0-11e7-8dce-513d553154f9.png)

Example data received:
<img width="704" alt="capture d ecran 2018-01-10 a 10 15 11" src="https://user-images.githubusercontent.com/9880577/34765626-4bbeb424-f5f2-11e7-8304-10cf0cb22448.png">

**Comment by bobeal** [comment]
Fixed in #415
